name = "lil-birdie-party"
main = "party/worker.ts"
compatibility_date = "2024-08-01"
workers_dev = true

[[durable_objects.bindings]]
name = "parties"
class_name = "WishlistServer"
script_name = "lil-birdie-party"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WishlistServer"]
